### PR TITLE
Revert "Merge branch 'pr/46'"

### PR DESCRIPTION
**Pull request by secondsun**
This reverts commit a917a0f5073eb8499ca0706dc20f2186652e38a4, reversing
changes made to 173b79e8bb9a55860c443df8966e9edc571bf425.

### CODE REVIEW

**Comment by danielpassos** [comment]
👍

**Comment by cotnic** [comment]
Will there be a new 3.1.2 version with this fix, or will the 3.1.1 version be updated? Thanks.

**Comment by danielpassos** [comment]
@cotnic `3.1.2`

**Comment by cotnic** [comment]
Is there any approximate time known for when the 3.1.2 version will be released? Since we would like to ship our application out as soon as possible. Thanks!

**Comment by danielpassos** [comment]
@cotnic No, but since it's a bug, it's a priority, as soon as I can double check it will be ship

**Comment by cotnic** [comment]
Ok, thank you very much for the fast responses and fix.

**Comment by uzdik-student** [comment]
Has this issue been fixed in 4.0.0 ?
If yes, should https://github.com/aerogear/aerogear-android-authz/blob/master/README.md be updated according to this bug fix ?

**Pull request merged**
