### PR TITLE
Fix token endpoint request

### PR DESCRIPTION
**Pull request by giancarloromeo**
Data should be sent through URL query parameters and not in the request body.

### CODE REVIEW

**Comment by secondsun** [comment]
@danielpassos :eyes: ?

**Comment by secondsun** [comment]
@giancarloromeo I saw your message in #aerogear on free node.  If you build your library locally with maven you can add MavenLocal to your android project's repositories and then just use your local image in the dependencies.  That *should* fix the error you were getting.  Don't copy the jar to your lib folder because then you will just end up adding the library twice and make dex angry.

**Comment by danielpassos** [comment]
👍

**Comment by cotnic** [comment]
Was this tested? Now that I've migrated from 3.1.0 to 3.1.1 I've got an error at login. If I revert back the login works again. As it seems the error happens at the exact location of this PR request. My stackTrace is: 

07-06 06:40:33.690 5751-5751/com.kumuluz.ccm.android.sample D/KeycloakHelper: Keycloak failure: AuthorizationException{error=invalid_request}
07-06 06:40:33.690 5751-5751/com.kumuluz.ccm.android.sample W/System.err: AuthorizationException{error=invalid_request}
07-06 06:40:33.690 5751-5751/com.kumuluz.ccm.android.sample W/System.err:     at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.runAccountAction(OAuth2AuthzService.java:278)
07-06 06:40:33.690 5751-5751/com.kumuluz.ccm.android.sample W/System.err:     at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.exchangeAuthorizationCodeForAccessToken(OAuth2AuthzService.java:208)
07-06 06:40:33.691 5751-5751/com.kumuluz.ccm.android.sample W/System.err:     at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.fetchAccessToken(OAuth2AuthzService.java:93)
07-06 06:40:33.691 5751-5751/com.kumuluz.ccm.android.sample W/System.err:     at org.jboss.aerogear.android.authorization.oauth2.OAuth2FetchAccess$1.doInBackground(OAuth2FetchAccess.java:51)
07-06 06:40:33.691 5751-5751/com.kumuluz.ccm.android.sample W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:304)
07-06 06:40:33.691 5751-5751/com.kumuluz.ccm.android.sample W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-06 06:40:33.691 5751-5751/com.kumuluz.ccm.android.sample W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-06 06:40:33.691 5751-5751/com.kumuluz.ccm.android.sample W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-06 06:40:33.691 5751-5751/com.kumuluz.ccm.android.sample W/System.err:     at java.lang.Thread.run(Thread.java:761)
07-06 06:40:33.691 5751-5751/com.kumuluz.ccm.android.sample D/LoginActivity: Login failed!

**Comment by secondsun** [comment]
Yeah, this was not right.  Among other things the OAuth spec says this behavior is wrong.  Reverting the PR

**Pull request merged**
